export const posts = [
  {
    id: 1, title: 'Building Habits That Actually Stick',
    excerpt: "Most habit advice focuses on motivation. The problem is motivation is temporary. Here's what the research says about lasting change.",
    category: 'Productivity', date: 'May 6, 2026', readTime: '5 min read', featured: true,
    content: [
      { type: 'p', text: "Most advice about habits focuses on motivation. The problem is that motivation ebbs and flows—it's tied to how rested you are, how stressed you feel, whether the weather is nice. Relying on it is like relying on the tide to move your boat." },
      { type: 'p', text: "James Clear's research, popularized in Atomic Habits, points toward a more reliable driver: environment design. When the cue for a behavior is unavoidable, the behavior becomes almost automatic." },
      { type: 'h2', text: 'The Two-Minute Rule' },
      { type: 'p', text: "The hardest part of any habit is starting. Make it take less than two minutes. Don't go for a run—just put on your shoes. The action is a door, and the two-minute version is the key." },
      { type: 'blockquote', text: "Motivation is what gets you started. Habit is what keeps you going." },
      { type: 'h2', text: 'Tracking Without Obsessing' },
      { type: 'p', text: "The real rule isn't never miss—it's never miss twice. One bad day is noise. Two is the start of a new pattern. The goal isn't a perfect record. It's a long one." },
    ],
  },
  {
    id: 2, title: 'The Case for Slow Design',
    excerpt: "Fast design tools have made it easier than ever to produce something that looks polished. But there's a growing case for going deliberately slower.",
    category: 'Design', date: 'April 28, 2026', readTime: '4 min read', featured: false,
    content: [
      { type: 'p', text: "We live in an era of fast design. Figma templates in thirty seconds, AI-generated UI in minutes. But there's a growing case for going slower—deliberately, on purpose." },
      { type: 'h2', text: 'The Problem with Instant' },
      { type: 'p', text: "Speed tends to surface the obvious. Real insights usually live past the point of comfort. They require sitting with a problem long enough to get bored with the easy answers." },
      { type: 'blockquote', text: "The best solutions often feel inevitable once you find them. That feeling doesn't come from the first sketch." },
      { type: 'h2', text: 'When Speed Wins' },
      { type: 'p', text: "Fast design has its place: prototyping hypotheses, validating direction, shipping something to learn from. The trick is knowing which mode you're in." },
    ],
  },
  {
    id: 3, title: 'Tariffs Struck Down: What It Means for Your Books',
    excerpt: "A federal court just ruled Trump's 10% global tariffs illegal — and ordered refunds with interest. For businesses and accountants, the real work is just beginning.",
    category: 'Finance', date: 'May 10, 2026', readTime: '5 min read', featured: false,
    content: [
      { type: 'p', text: "On May 7, 2026, a three-judge panel at the US Court of International Trade delivered a landmark ruling: the 10% global import tariffs imposed under Section 122 of the Trade Act of 1974 are unlawful. The court didn't just strike them down — it ordered that illegally collected tariffs 'shall be refunded with interest as provided by law.' That last part is where accountants need to sit up and pay attention." },
      { type: 'h2', text: 'What Just Happened' },
      { type: 'p', text: "Section 122 of the Trade Act — a provision that had never previously been invoked — was the legal hook used to justify these tariffs. A coalition of small businesses and 24 mostly Democrat-led states challenged the legality, and the court sided with them. The ruling is significant but not yet final — the administration has already appealed, which means enforcement may be delayed by 30 days or more." },
      { type: 'h2', text: "The Accounting Problem Nobody's Talking About" },
      { type: 'p', text: "Since these tariffs were in effect, companies have been recording them as a cost of importing goods — baked into Cost of Goods Sold (COGS) on the income statement, or sitting in inventory valuations on the balance sheet. Now, with refunds potentially on the table, those numbers may need to be revisited." },
      { type: 'blockquote', text: "When a tariff you paid as a business cost turns into a receivable, your books don't update themselves." },
      { type: 'h2', text: 'Three Things Accountants Are Dealing With Right Now' },
      { type: 'p', text: "First, how to recognise the expected refund. Under US GAAP, you can't record a receivable until it's probable and estimable. With an active appeal in progress, the cautious move is to disclose the potential refund in the notes to financial statements — without booking it as income just yet." },
      { type: 'p', text: "Second, inventory values. If goods imported under these tariffs are still sitting in a warehouse, their carrying value includes that tariff cost. If a refund comes through, that cost may need to be reversed — reducing inventory value and eventually COGS when those goods are sold." },
      { type: 'p', text: "Third, the interest component. The court specifically said refunds come with interest. Interest income has its own treatment under ASC 835, and timing matters — you'll need to track exactly when each tariff was paid to calculate what's owed." },
      { type: 'h2', text: 'What Should Businesses Do Now?' },
      { type: 'p', text: "Don't rush to restate anything. The appeal means this ruling could still be overturned. The smart move right now is to document every tariff payment made under these rules — amounts, dates, and the goods they applied to. That paper trail will be essential whether the refund comes through or the ruling is reversed." },
      { type: 'blockquote', text: "In accounting, the hardest entries to make are the ones where you're waiting for the law to catch up." },
      { type: 'h2', text: 'The Bigger Picture' },
      { type: 'p', text: "This ruling is a reminder that government policy changes are an accounting event. Every tariff, every tax change, every regulatory shift ripples through financial statements in ways that aren't always obvious. The businesses that handle this best will be the ones with clean records, proactive accountants, and the discipline to wait for certainty before booking the win." },
    ],
  },
]
