export const posts = [
  {
    id: 1,
    title: 'The SEC Just Proposed Half the Reporting. Accountants Have Questions.',
    excerpt: "The SEC wants to let public companies file financial reports twice a year instead of four times. It sounds like less work. It's more complicated than that.",
    category: 'Regulation', date: 'May 9, 2026', readTime: '6 min read', featured: true,
    content: [
      { type: 'p', text: "On May 5, 2026, the Securities and Exchange Commission proposed something that will reshape how public companies share their finances: an optional switch from quarterly reporting on Form 10-Q to semi-annual reporting on a new Form 10-S. Companies could file just one interim report per year instead of three. It sounds like a gift. For accountants and investors, it raises a lot of questions." },
      { type: 'h2', text: "What's Actually Being Proposed" },
      { type: 'p', text: "Under the proposal, companies would elect semi-annual reporting annually by checking a box on their Form 10-K. Instead of filing three quarterly reports, they'd file one six-month report covering the same content as a 10-Q — just for a longer period. The SEC is also amending Regulation S-X, the rulebook that governs financial statement requirements for periodic filings and registration statements." },
      { type: 'blockquote', text: "Less frequent reporting doesn't mean less rigorous reporting. It means the stakes for each filing go up." },
      { type: 'h2', text: 'Why This Matters for Accountants' },
      { type: 'p', text: "Quarterly reporting has been the rhythm of financial life for decades. It drives audit cycles, shapes how finance teams plan their workloads, and sets investor expectations. A shift to semi-annual reporting doesn't halve the work — it concentrates it. Six-month periods capture more transactions, more estimates, and more judgment calls than a quarter ever does." },
      { type: 'p', text: "There's also the question of interim reviews. Auditors currently perform limited reviews of quarterly filings under AS 4105. With a six-month period, those procedures would cover a larger pool of transactions with the same level of scrutiny — an area that auditing standards boards will need to address before this becomes reality." },
      { type: 'h2', text: 'The Investor Transparency Debate' },
      { type: 'p', text: "Critics argue that quarterly reporting keeps companies accountable. When investors get financial data every 90 days, there are fewer places to hide a bad trend. Switch to six-month intervals, and a single weak quarter can be quietly smoothed out before the market ever sees it." },
      { type: 'blockquote', text: "Disclosure intervals matter. The longer the gap, the harder it becomes to pinpoint exactly when something went wrong." },
      { type: 'h2', text: 'Who This Actually Helps' },
      { type: 'p', text: "Smaller public companies are the most likely beneficiaries. Quarterly reporting is expensive — compliance costs, audit fees, and the management time required to prepare each filing are real burdens for companies with lean finance teams. A semi-annual option gives them room to breathe without eliminating the annual audit that provides the market's deepest level of assurance." },
      { type: 'h2', text: 'What Happens Next' },
      { type: 'p', text: "The SEC is seeking public comment. Nothing changes until rules are finalised, and the proposal is optional — companies can still report quarterly if they choose. But the direction is clear: regulators are signalling that the quarterly cadence isn't sacred. Whether that's progress or a warning sign depends on which side of the balance sheet you're sitting on." },
    ],
  },
  {
    id: 2,
    title: 'Tariffs Struck Down: What It Means for Your Books',
    excerpt: "A federal court just ruled Trump's 10% global tariffs illegal — and ordered refunds with interest. For businesses and accountants, the real work is just beginning.",
    category: 'Finance', date: 'May 8, 2026', readTime: '5 min read', featured: false,
    content: [
      { type: 'p', text: "On May 7, 2026, a three-judge panel at the US Court of International Trade delivered a landmark ruling: the 10% global import tariffs imposed under Section 122 of the Trade Act of 1974 are unlawful. The court didn't just strike them down — it ordered that illegally collected tariffs 'shall be refunded with interest as provided by law.' That last part is where accountants need to sit up and pay attention." },
      { type: 'h2', text: 'What Just Happened' },
      { type: 'p', text: "Section 122 of the Trade Act — a provision that had never previously been invoked — was the legal hook used to justify these tariffs. A coalition of small businesses and 24 mostly Democrat-led states challenged the legality, and the court sided with them. The ruling is significant but not yet final — the administration has already appealed, which means enforcement may be delayed by 30 days or more." },
      { type: 'h2', text: "The Accounting Problem Nobody's Talking About" },
      { type: 'p', text: "Since these tariffs were in effect, companies have been recording them as a cost of importing goods — baked into Cost of Goods Sold (COGS) on the income statement, or sitting in inventory valuations on the balance sheet. Now, with refunds potentially on the table, those numbers may need to be revisited." },
      { type: 'blockquote', text: "When a tariff you paid as a business cost turns into a receivable, your books don't update themselves." },
      { type: 'h2', text: 'Three Things Accountants Are Dealing With Right Now' },
      { type: 'p', text: "First, how to recognise the expected refund. Under US GAAP, you can't record a receivable until it's probable and estimable. With an active appeal in progress, the cautious move is to disclose the potential refund in the notes to financial statements — without booking it as income just yet." },
      { type: 'p', text: "Second, inventory values. If goods imported under these tariffs are still sitting in a warehouse, their carrying value includes that tariff cost. If a refund comes through, that cost may need to be reversed — reducing inventory value and eventually COGS when those goods are sold." },
      { type: 'p', text: "Third, the interest component. The court specifically said refunds come with interest. Interest income has its own treatment under ASC 835, and timing matters — you'll need to track exactly when each tariff was paid to calculate what's owed." },
      { type: 'h2', text: 'What Should Businesses Do Now?' },
      { type: 'p', text: "Don't rush to restate anything. The appeal means this ruling could still be overturned. The smart move right now is to document every tariff payment made under these rules — amounts, dates, and the goods they applied to. That paper trail will be essential whether the refund comes through or the ruling is reversed." },
      { type: 'blockquote', text: "In accounting, the hardest entries to make are the ones where you're waiting for the law to catch up." },
      { type: 'h2', text: 'The Bigger Picture' },
      { type: 'p', text: "This ruling is a reminder that government policy changes are an accounting event. Every tariff, every tax change, every regulatory shift ripples through financial statements in ways that aren't always obvious. The businesses that handle this best will be the ones with clean records, proactive accountants, and the discipline to wait for certainty before booking the win." },
    ],
  },
  {
    id: 3,
    title: "Cloudflare's Record Revenue, 1,100 Layoffs, and What the Books Will Show",
    excerpt: "Cloudflare just reported its highest-ever revenue quarter — then cut 20% of its staff. For accountants, the earnings report is only half the story.",
    category: 'Tech', date: 'May 9, 2026', readTime: '5 min read', featured: false,
    content: [
      { type: 'p', text: "On May 8, 2026, Cloudflare announced it was laying off 1,100 employees — roughly 20% of its entire workforce — even as the company reported the highest quarterly revenue in its history. The stated reason: AI has made those roles redundant. The stock dropped 24%. For anyone reading the financial statements, there's a lot more to unpack." },
      { type: 'h2', text: 'What Gets Booked as a Restructuring Charge' },
      { type: 'p', text: "When a company announces layoffs of this scale, the first accounting question is: when does this hit the income statement? Under ASC 420 (Exit or Disposal Cost Obligations), companies must recognise one-time termination benefits when management commits to a plan and communicates it to employees. Cloudflare did both on May 7. That means these costs land in Q2 2026 — not Q1, even though the announcement came alongside Q1 earnings." },
      { type: 'blockquote', text: "The quarter you announce a restructuring and the quarter you account for it aren't always the same." },
      { type: 'h2', text: "The Severance Package Is Unusually Generous — and That Has a Number" },
      { type: 'p', text: "Cloudflare offered departing employees full base pay through the end of 2026 — potentially seven or more months of salary. It also waived equity vesting cliffs and accelerated vesting to August 15. These aren't standard severance terms. Accelerated equity vesting means the remaining unrecognised stock-based compensation expense gets recognised in one hit — all the equity that would have vested over coming years gets expensed immediately in Q2." },
      { type: 'p', text: "For a company of Cloudflare's size and compensation structure, that acceleration alone could represent tens of millions of dollars of non-cash expense hitting a single quarter." },
      { type: 'h2', text: 'Record Revenue, But What About Profit?' },
      { type: 'p', text: "Cloudflare's Q1 revenue grew 25% year over year — a genuine record. But revenue is not profit. The restructuring charges, severance costs, and accelerated equity expense that land in Q2 will create a significant one-time hit to net income. Analysts will point to adjusted, non-GAAP figures that strip these out — but GAAP tells the full story, and for one quarter it won't look clean." },
      { type: 'blockquote', text: "Restructuring charges are a one-time expense in the press release. In the income statement, they're very real." },
      { type: 'h2', text: 'What to Watch in the Next Filing' },
      { type: 'p', text: "When Cloudflare files its Q2 2026 results, look closely at the restructuring charge line item, the stock-based compensation breakdown, and management's commentary on future headcount. Companies sometimes underestimate restructuring costs initially — if the charge is revised upward in Q3, that's a yellow flag. The underlying bet Cloudflare is making is clear: absorb the pain in one quarter, and let leaner operating costs improve margins from Q3 onwards." },
    ],
  },
]
