export const posts = [
  {
    id: 1, title: 'Building Habits That Actually Stick',
    excerpt: "Most habit advice focuses on motivation. The problem is motivation is temporary. Here's what the research says about lasting change.",
    category: 'Productivity', date: 'May 6, 2026', readTime: '5 min read', featured: true,
    content: [
      { type: 'p', text: "Most advice about habits focuses on motivation. The problem is that motivation ebbs and flows—it's tied to how rested you are, how stressed you feel, whether the weather is nice. Relying on it is like relying on the tide to move your boat." },
      { type: 'p', text: "James Clear's research, popularized in Atomic Habits, points toward a more reliable driver: environment design. When the cue for a behavior is unavoidable, the behavior becomes almost automatic." },
      { type: 'h2', text: 'The Two-Minute Rule' },
      { type: 'p', text: "The hardest part of any habit is starting. Make it take less than two minutes. Don't go for a run—just put on your shoes. The action is a door, and the two-minute version is the key." },
      { type: 'blockquote', text: "Motivation is what gets you started. Habit is what keeps you going." },
      { type: 'h2', text: 'Tracking Without Obsessing' },
      { type: 'p', text: "The real rule isn't never miss—it's never miss twice. One bad day is noise. Two is the start of a new pattern. The goal isn't a perfect record. It's a long one." },
    ],
  },
  {
    id: 2, title: 'The Case for Slow Design',
    excerpt: "Fast design tools have made it easier than ever to produce something that looks polished. But there's a growing case for going deliberately slower.",
    category: 'Design', date: 'April 28, 2026', readTime: '4 min read', featured: false,
    content: [
      { type: 'p', text: "We live in an era of fast design. Figma templates in thirty seconds, AI-generated UI in minutes. But there's a growing case for going slower—deliberately, on purpose." },
      { type: 'h2', text: 'The Problem with Instant' },
      { type: 'p', text: "Speed tends to surface the obvious. Real insights usually live past the point of comfort. They require sitting with a problem long enough to get bored with the easy answers." },
      { type: 'blockquote', text: "The best solutions often feel inevitable once you find them. That feeling doesn't come from the first sketch." },
      { type: 'h2', text: 'When Speed Wins' },
      { type: 'p', text: "Fast design has its place: prototyping hypotheses, validating direction, shipping something to learn from. The trick is knowing which mode you're in." },
    ],
  },
  {
    id: 3, title: 'Why Side Projects Keep You Sharp',
    excerpt: "Side projects have a reputation as procrastination in disguise. But the best engineers I know all have them.",
    category: 'Dev', date: 'April 15, 2026', readTime: '6 min read', featured: false,
    content: [
      { type: 'p', text: "Side projects are where the most interesting learning happens. The distinction is usually intent—a project built to solve a real problem teaches you something genuine." },
      { type: 'h2', text: 'Learning Without Permission' },
      { type: 'p', text: "At work, the stack is chosen and the patterns are established. Side projects are where you can try the thing you've been curious about—the new language, the weird architecture." },
      { type: 'blockquote', text: "The projects that teach you the most are the ones where you hit walls you didn't expect." },
      { type: 'h2', text: 'The Compounding Effect' },
      { type: 'p', text: "The engineers I most respect have a long history of side projects—a graveyard of half-finished experiments and lessons learned. That graveyard is the credential." },
    ],
  },
  {
    id: 4, title: 'Learning in Public: One Year Later',
    excerpt: "A year ago I started sharing my work online before I felt ready. Here's what actually happened.",
    category: 'Career', date: 'April 3, 2026', readTime: '7 min read', featured: false,
    content: [
      { type: 'p', text: "A year ago I started sharing what I was working on before I felt ready. The fear was that I'd look incompetent. The reality was almost the opposite." },
      { type: 'h2', text: 'What Actually Happened' },
      { type: 'p', text: "The posts I was most uncertain about often got the best responses—because readers aren't looking for finished knowledge, they're looking for honest thinking." },
      { type: 'blockquote', text: "Learning in public isn't about broadcasting your ignorance. It's about making your curiosity visible." },
      { type: 'h2', text: 'The Compound Interest' },
      { type: 'p', text: "Something you write once can help someone for years. That asymmetry—small effort, long tail of value—is hard to find in most activities." },
    ],
  },
  {
    id: 5, title: 'Getting Better at Deep Work',
    excerpt: "Cal Newport's ideas changed how I think about focus. Here's how I actually put them into practice.",
    category: 'Productivity', date: 'March 20, 2026', readTime: '5 min read', featured: false,
    content: [
      { type: 'p', text: "Deep work isn't the default. It requires deliberate construction. Most knowledge workers switch contexts every eight minutes." },
      { type: 'h2', text: 'Scheduling It Like a Meeting' },
      { type: 'p', text: "Treat deep work blocks like appointments. Not I'll find time but Tuesday 9 to 11am: deep work. The block is non-negotiable." },
      { type: 'blockquote', text: "Clarity about what you're protecting is a prerequisite for protecting it." },
      { type: 'h2', text: 'The Shutdown Ritual' },
      { type: 'p', text: "A deliberate end-of-workday process closes all open loops and lets you actually disengage. Without it, work bleeds into evenings." },
    ],
  },
  {
    id: 6, title: 'The Tech I Actually Use in 2026',
    excerpt: "A practical rundown of the tools that have earned a permanent spot in my workflow.",
    category: 'Tech', date: 'March 8, 2026', readTime: '4 min read', featured: false,
    content: [
      { type: 'p', text: "Every year I audit what's actually in my workflow. The delta is usually enlightening. Here's what made the cut in 2026." },
      { type: 'h2', text: 'Daily Drivers' },
      { type: 'p', text: "For writing, it's still plain text and Markdown. The portability is unbeatable and the friction is basically zero." },
      { type: 'h2', text: 'What I Dropped' },
      { type: 'p', text: "Three task management apps I no longer use. I spent more time organizing tasks than doing them. A plain text file with today's three priorities won." },
      { type: 'blockquote', text: "The best tool is usually the one with the smallest gap between intention and action." },
    ],
  },
]